name: CI

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest

    # needed for criterion
    container:
        image: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v2
    - name: compile binary
      run: |
          make
          make re
          make fclean
    - name: make tests_run
      run: |
        make tests_run
        gcovr --exclude tests/
        gcovr --exclude tests/ --branches
        make fclean
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
          sudo apt install -y doxygen clang-tidy
    - name: clang-format lint
      run: make CI

    - name: compile Doxygen docs
      run: make docs